site_name: loxilb v0.9.3
site_url: https://loxilb-io.github.io/loxilbdocs 
theme:
    name: mkdocs
    features:
        - navigation.sections
    analytics:
        gtag: G-21G7NBL2BN 

nav:
  - Home: index.md
  - How-To Guides:
      - How-To - kube-loxilb: kube-loxilb.md
      - How-To - service-group zones: service-zones.md
      - How-To - high-availability with loxilb: ha-deploy.md
      - How-To - build/run: run.md
      - How-To - loxilb in standalone mode: standalone.md
      - How-To - cmd configuration: cmd.md
      - How-To - debugging: debugging.md
      - How-To - access end-points outside K8s: ext-ep.md
      - How-To - Deploy multi-server K3s HA with loxilb: k3s-multi-master.md
  - Getting started with different K8s distributions & tools:
      - loxilb as ext-cluster pod:
          - K3s - loxilb with default flannel: k3s_quick_start_flannel.md
          - K3s - loxilb with calico: k3s_quick_start_calico.md
          - K3s - loxilb with cilium: quick_start_with_cilium.md
          - K3s - loxilb with default kube-router networking: k0s_quick_start.md
      - loxilb as in-cluster pod:
          - K3s - loxilb in-cluster mode: k3s_quick_start_incluster.md
          - K0s - loxilb in-cluster mode: k0s_quick_start_incluster.md
          - MicroK8s - loxilb in-cluster mode: microk8s_quick_start_incluster.md
      - loxilb as service-proxy:
          - K3s - loxilb service-proxy with flannel: service-proxy-flannel.md
          - K3s - loxilb service-proxy with calico: service-proxy-calico.md
  - Knowledge Base:
      - What is eBPF: ebpf.md
      - What is k8s service - load-balancer: lb.md
      - Architecture in brief: arch.md
      - Code organization: code.md
      - eBPF internals: loxilbebpf.md
      - NAT Modes of loxilb: nat.md
      - loxilb load-balancer algorithms: lb-algo.md
      - Developer's guide to loxicmd: cmd-dev.md
      - Developer's guide to loxilb API: api-dev.md
      - loxilb api-reference: api.md
      - Performance Report: perf.md
      - Development Roadmap: roadmap.md
      - Contribution Guide: contribute.md
      - System Requirements: requirements.md
      - Frequenctly Asked Questions- FAQs: faq.md
  - Blogs:
      - K8s - Elevating Cluster Networking: https://www.loxilb.io/post/loxilb-cluster-networking-elevating-k8s-networking-capabilities
      - eBPF - Map Sync using Go: https://www.loxilb.io/post/state-synchronization-of-ebpf-maps-using-go-a-tale-of-two-frameworks
      - K8s in-cluster service LB with LoxiLB: https://www.loxilb.io/post/k8s-nuances-of-in-cluster-external-service-lb-with-loxilb
      - K8s - Introducing SCTP Multihoming with LoxiLB: https://www.loxilb.io/post/k8s-introducing-sctp-multihoming-functionality-with-loxilb
      - Hyperscale anycast load balancing with HA: https://www.loxilb.io/post/loxilb-anycast-service-load-balancing-with-high-availability
      - Getting started with loxilb on Amazon EKS: https://www.loxilb.io/post/loxilb-load-balancer-setup-on-eks
      - K8s - Deploying hitless Load-Balancing: https://www.loxilb.io/post/k8s-deploying-hitless-and-ha-load-balancing
      - Ipv6 migration in Kubernetes made easy: https://www.loxilb.io/post/k8s-exposing-ipv4-services-externally-as-ipv6
      - Load-balancer Perf comparison on Amazon Graviton2: https://www.loxilb.io/post/running-loxilb-on-aws-graviton2-based-ec2-instance
      - Community Posts:
        - 5G SCTP LoadBalancer Using loxilb: https://futuredon.medium.com/5g-sctp-loadbalancer-using-loxilb-b525198a9103
        - 5G Uplink Classifier Using loxilb: https://futuredon.medium.com/5g-uplink-classifier-using-loxilb-7593a4d66f4c
        - K3s - Using loxilb as external service lb: https://cloudybytes.medium.com/k3s-using-loxilb-as-external-service-lb-2ea4ce61e159
        - 5G SCTP LoadBalancer Using LoxiLB Applying on free5GC: https://medium.com/@ben0978327139/5g-sctp-loadbalancer-using-loxilb-applying-on-free5gc-b5c05bb723f0
extra:
    version: v0.9.3 (Latest)

extra_css:
  - stylesheets/extra.css

plugins:
  - mermaid2
