site_name: loxilb v0.8.7
site_url: https://loxilb-io.github.io/loxilbdocs 
theme:
    name: mkdocs
    features:
        - navigation.sections
    analytics:
        gtag: G-21G7NBL2BN 

nav:
  - Home: index.md
  - How-To Guides:
      - How-To - build/run: run.md
      - How-To - configuration: cmd.md
      - How-To - kube-loxilb: kube-loxilb.md
      - How-To - ccm plugin: ccm.md
      - How-To - debug: debugging.md
      - How-To - loxilb with calico bgp: integrate_bgp_eng.md
      - How-To - loxilb in standalone mode: standalone.md
      - How-To - loxilb Web-APIs: api.md
  - Knowledge Base:
      - What is eBPF: ebpf.md
      - What is k8s service - load-balancer: lb.md
      - Architecture in brief: arch.md
      - Code organization: code.md
      - eBPF internals: loxilbebpf.md
      - NAT Modes of loxilb: nat.md
      - Developer's guide to loxicmd: cmd-dev.md
      - Developer's guide to loxilb API: api-dev.md
      - Performance Report: perf.md
      - Development Roadmap: roadmap.md
      - Contribution Guide: contribute.md
      - System Requirements: requirements.md
      - Frequenctly Asked Questions- FAQs: faq.md
  - Blogs:
      - K8s - Introducing SCTP Multihoming with LoxiLB: https://www.loxilb.io/post/k8s-introducing-sctp-multihoming-functionality-with-loxilb
      - Hyperscale anycast load balancing with HA: https://www.loxilb.io/post/loxilb-anycast-service-load-balancing-with-high-availability
      - Getting started with loxilb on Amazon EKS: https://www.loxilb.io/post/loxilb-load-balancer-setup-on-eks
      - K8s - Deploying hitless Load-Balancing: https://www.loxilb.io/post/k8s-deploying-hitless-and-ha-load-balancing
      - Ipv6 migration in Kubernetes made easy: https://www.loxilb.io/post/k8s-exposing-ipv4-services-externally-as-ipv6
      - Load-balancer Perf comparison on Amazon Graviton2: https://www.loxilb.io/post/running-loxilb-on-aws-graviton2-based-ec2-instance
      - Community Posts:
        - 5G SCTP LoadBalancer Using loxilb: https://futuredon.medium.com/5g-sctp-loadbalancer-using-loxilb-b525198a9103
        - 5G Uplink Classifier Using loxilb: https://futuredon.medium.com/5g-uplink-classifier-using-loxilb-7593a4d66f4c
        - K3s - Using loxilb as external service lb: https://cloudybytes.medium.com/k3s-using-loxilb-as-external-service-lb-2ea4ce61e159
        - 5G SCTP LoadBalancer Using LoxiLB Applying on free5GC: https://medium.com/@ben0978327139/5g-sctp-loadbalancer-using-loxilb-applying-on-free5gc-b5c05bb723f0
extra:
    version: v0.8.7 (Latest)

extra_css:
  - stylesheets/extra.css

plugins:
  - mermaid2
