site_name: LoxiLB
site_url: https://github.com/loxilb-io/loxilbdocs
repo_name: loxilb-io/loxilb
repo_url: https://github.com/loxilb-io/loxilb
theme:
    name: material
    logo: photos/loxilb-logo.png
    features:
        - navigation.path
        - navigation.instant
        - navigation.tracking
        - navigation.indexes
        - navigation.top
        - search.suggest
    analytics:
        gtag: G-21G7NBL2BN 
    icon:
        repo: fontawesome/brands/github
    palette:
        - scheme: default
          media: "(prefers-color-scheme: light)"
          primary: indigo
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - scheme: slate
          media: "(prefers-color-scheme: dark)"
          primary: black
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
nav:
  - LoxiLB: index.md
  - Architectural Considerations:
      - Understanding loxilb deployment in K8s with kube-loxilb: kube-loxilb.md
      - Understanding High-availability with loxilb: ha-deploy.md
  - Getting Started:
      - External Cluster Mode:
          - K3s/loxilb with default flannel: k3s_quick_start_flannel.md
          - K3s/loxilb with calico: k3s_quick_start_calico.md
          - K3s/loxilb with cilium: quick_start_with_cilium.md
          - K0s/loxilb with kube-router: k0s_quick_start.md
      - In-Cluster Mode:
          - K3s/loxilb in-cluster mode: k3s_quick_start_incluster.md
          - K0s/loxilb in-cluster mode: k0s_quick_start_incluster.md
          - MicroK8s/loxilb in-cluster mode: microk8s_quick_start_incluster.md
      - Service-Proxy Mode:
          - K3s/loxilb service-proxy with flannel: service-proxy-flannel.md
          - K3s/loxilb service-proxy with calico: service-proxy-calico.md
      - Kubernestes Ingress Mode
          - k3s/Run loxilb-ingress: loxilb-ingress.md
      - Standalone Mode: standalone.md
  - Advanced Guides:
      - How-To - service-group zones: service-zones.md
      - How-To - access end-points outside K8s: ext-ep.md
      - How-To - Deploy multi-server K3s HA with loxilb: k3s-multi-master.md
  - Knowledge Base:
      - What is eBPF: ebpf.md
      - What is k8s service - load-balancer: lb.md
      - Architecture in brief: arch.md
      - Code organization: code.md
      - eBPF internals: loxilbebpf.md
      - NAT Modes of loxilb: nat.md
      - loxilb load-balancer algorithms: lb-algo.md
      - Manual steps to build/run: run.md
      - Debugging loxilb: debugging.md
      - Developer's guide to loxicmd: cmd-dev.md
      - Developer's guide to loxilb API: api-dev.md
      - loxilb api-reference: api.md
      - Performance Report: perf.md
      - Development Roadmap: roadmap.md
      - Contribution Guide: contribute.md
      - System Requirements: requirements.md
      - Frequenctly Asked Questions- FAQs: faq.md
  - Blogs:
      - K8s - Elevating Cluster Networking: https://www.loxilb.io/post/loxilb-cluster-networking-elevating-k8s-networking-capabilities
      - eBPF - Map Sync using Go: https://www.loxilb.io/post/state-synchronization-of-ebpf-maps-using-go-a-tale-of-two-frameworks
      - K8s in-cluster service LB with LoxiLB: https://www.loxilb.io/post/k8s-nuances-of-in-cluster-external-service-lb-with-loxilb
      - K8s - Introducing SCTP Multihoming with LoxiLB: https://www.loxilb.io/post/k8s-introducing-sctp-multihoming-functionality-with-loxilb
      - Hyperscale anycast load balancing with HA: https://www.loxilb.io/post/loxilb-anycast-service-load-balancing-with-high-availability
      - Getting started with loxilb on Amazon EKS: https://www.loxilb.io/post/loxilb-load-balancer-setup-on-eks
      - K8s - Deploying hitless Load-Balancing: https://www.loxilb.io/post/k8s-deploying-hitless-and-ha-load-balancing
      - Ipv6 migration in Kubernetes made easy: https://www.loxilb.io/post/k8s-exposing-ipv4-services-externally-as-ipv6
      - Load-balancer Perf comparison on Amazon Graviton2: https://www.loxilb.io/post/running-loxilb-on-aws-graviton2-based-ec2-instance
      - Community Posts:
        - 5G SCTP LoadBalancer Using loxilb: https://futuredon.medium.com/5g-sctp-loadbalancer-using-loxilb-b525198a9103
        - 5G Uplink Classifier Using loxilb: https://futuredon.medium.com/5g-uplink-classifier-using-loxilb-7593a4d66f4c
        - K3s - Using loxilb as external service lb: https://cloudybytes.medium.com/k3s-using-loxilb-as-external-service-lb-2ea4ce61e159
        - 5G SCTP LoadBalancer Using LoxiLB Applying on free5GC: https://medium.com/@ben0978327139/5g-sctp-loadbalancer-using-loxilb-applying-on-free5gc-b5c05bb723f0
     
extra:
    version: v0.9.5 (Latest)
    homepage: https://www.loxilb.io/ 

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - def_list
  - tables
  - attr_list
  - md_in_html
  - toc:
      title: On this page
  - pymdownx.tasklist:
      custom_checkbox: true
      
plugins:
  - mermaid2
  - search
  - autorefs
