name: LoxiLB-Docs 
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'     
        required: true
        default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-mermaid2-plugin mkdocs-autorefs mkdocs-material mike jq
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get the latest version
        run: echo "version=$(curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/loxilb-io/loxilb/releases/latest" | jq -r .name)" >> "$GITHUB_ENV"
      - name: Publish docs for latest
        if: github.event.inputs.tagName == '' 
        #run: mkdocs gh-deploy
        run: |
            mike deploy --push --update-aliases main latest
            mike set-default main
      - name: Publish docs for given tag
        if: github.event.inputs.tagName != ''
        #run: mkdocs gh-deploy
        run: mike deploy --push ${{ github.event.inputs.tagName }} --allow-empty
